/**
 * E2E tests for silent fallback behaviour.
 *
 * Server is started (via playwright.fallback.config.ts) with an invalid
 * primary model (`CHAT_MODEL=gemini-3-flash`) and OpenAI as the fallback
 * provider. Every turn should:
 *   - never render the "Something went wrong" banner
 *   - successfully render an assistant response
 *   - be persisted with provider=openai (via FileConversationBackend)
 *
 * This is the multi-message regression test for the v0.3.20 fixes:
 *   - silent fallback: no transient SSE error events leak to the UI
 *   - cross-provider model scrub: primary's saved model id ("gemini-3-flash")
 *     must NOT be passed to OpenAI; saved state must be reusable across turns
 *
 * Run: `npm run test:e2e:fallback` (from demo/)
 *
 * Requires GOOGLE_API_KEY (or GEMINI_API_KEY) AND OPENAI_API_KEY in env.
 * Tests are skipped if either key is missing.
 */

import { test, expect, type Page } from "@playwright/test";
import { readFileSync, existsSync, rmSync } from "fs";
import path from "path";

const HAS_GEMINI_KEY = !!(process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY);
const HAS_OPENAI_KEY = !!process.env.OPENAI_API_KEY;
const HAS_KEYS = HAS_GEMINI_KEY && HAS_OPENAI_KEY;

const CONV_DIR = path.join(__dirname, "..", "data", "conversations-fallback-e2e");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function waitForChatReady(page: Page) {
  await page.locator(".aui-composer-input").waitFor({ state: "visible", timeout: 15_000 });
}

async function sendMessage(page: Page, text: string) {
  const input = page.locator(".aui-composer-input");
  await input.fill(text);
  await page.locator(".aui-composer-send").click();
}

async function waitForStreamingDone(page: Page) {
  // Send button reappears once streaming completes
  await page.locator(".aui-composer-send").waitFor({ state: "visible", timeout: 120_000 });
}

/** Find the most recent assistant message and return its visible text. */
async function lastAssistantText(page: Page): Promise<string> {
  const messages = page.locator(".aui-assistant-message-content");
  await messages.last().waitFor({ state: "visible", timeout: 60_000 });
  return (await messages.last().textContent()) ?? "";
}

/** Returns true if any "Something went wrong" / error-banner is currently rendered. */
async function hasErrorBanner(page: Page): Promise<boolean> {
  // assistant-ui renders SSE `error` events as a styled error block.
  // Match common phrasing — both the generic text and the v0.3.17 retry
  // notice that we explicitly stopped emitting in v0.3.18.
  const text = await page.locator("body").textContent();
  if (!text) return false;
  return /Something went wrong/i.test(text)
      || /Primary provider failed/i.test(text)
      || /Empty response from model/i.test(text)
      || /Invalid conversation data/i.test(text);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test.describe("silent fallback (primary=gemini-3-flash invalid, fallback=openai)", () => {
  test.skip(!HAS_KEYS, "Requires both GEMINI/GOOGLE_API_KEY and OPENAI_API_KEY");

  test.beforeEach(async ({ page }) => {
    // Start each test on a fresh thread so prior turns don't leak in.
    // The widget creates a new local thread on first visit; reload guarantees one.
    await page.goto("/");
    await waitForChatReady(page);
  });

  test.afterAll(async () => {
    // Clean up conversation state generated by this run so the next run
    // starts from scratch and can't be polluted by stale on-disk files.
    if (existsSync(CONV_DIR)) {
      rmSync(CONV_DIR, { recursive: true, force: true });
    }
  });

  test("first message: primary fails silently, fallback streams response", async ({ page }) => {
    await sendMessage(page, "What is 2 + 2? Answer with just the number.");
    await waitForStreamingDone(page);

    expect(await hasErrorBanner(page)).toBe(false);

    const text = await lastAssistantText(page);
    expect(text.length).toBeGreaterThan(0);
    // OpenAI should answer "4" somewhere in its response.
    expect(text).toMatch(/4/);
  });

  test("multi-turn: 3 sequential messages, every turn silently uses fallback", async ({ page }) => {
    const prompts = [
      { q: "What is 2+2? Answer with just the number.",  expect: /4/  },
      { q: "And 3+3? Just the number.",                  expect: /6/  },
      { q: "Now 5*5? Just the number.",                  expect: /25/ },
    ];

    for (const [i, { q, expect: exp }] of prompts.entries()) {
      const expectedCount = i + 1;
      const messages = page.locator(".aui-assistant-message-root");

      await sendMessage(page, q);

      // Wait for the new assistant message to appear (streaming may not have
      // started by the time the send button reappears, so anchor the wait
      // on message-count growing rather than button state).
      await expect(messages, `turn ${expectedCount}: assistant message should appear`)
        .toHaveCount(expectedCount, { timeout: 120_000 });

      // Now wait for streaming to settle by polling for stable message text.
      let lastText = "";
      let stableCount = 0;
      for (let attempt = 0; attempt < 60; attempt++) {
        const current = (await messages.last().textContent()) ?? "";
        if (current && current === lastText) {
          stableCount++;
          if (stableCount >= 3) break; // text unchanged for ~1.5s → done
        } else {
          stableCount = 0;
        }
        lastText = current;
        await page.waitForTimeout(500);
      }

      expect(await hasErrorBanner(page), `turn ${expectedCount}: error banner should not appear`).toBe(false);
      expect(lastText, `turn ${expectedCount}: response empty`).not.toBe("");
      expect(lastText, `turn ${expectedCount}: response did not contain expected answer`).toMatch(exp);
    }
  });

  test("on-disk persistence: turns saved with provider=openai (the fallback)", async ({ page }) => {
    await sendMessage(page, "Quick test: respond with the word 'ok'.");
    await waitForStreamingDone(page);
    expect(await hasErrorBanner(page)).toBe(false);

    // Find the conversation.json the demo's FileConversationBackend wrote.
    const fs = await import("fs");
    const dirs = fs.readdirSync(CONV_DIR, { withFileTypes: true })
      .filter(d => d.isDirectory())
      .map(d => d.name);
    expect(dirs.length, "expected at least one persisted thread").toBeGreaterThan(0);

    // The last-modified directory holds the active thread for this test.
    const newest = dirs
      .map(name => ({ name, mtime: fs.statSync(path.join(CONV_DIR, name)).mtimeMs }))
      .sort((a, b) => b.mtime - a.mtime)[0];

    const convPath = path.join(CONV_DIR, newest.name, "conversation.json");
    const data = JSON.parse(readFileSync(convPath, "utf-8"));

    expect(data.formatVersion, "formatVersion must be present").toBeTruthy();
    expect(data.provider, "thread should have flipped to fallback provider").toBe("openai");
    expect(data.turns?.length, "at least one turn persisted").toBeGreaterThan(0);
    // Critical: the saved model must NOT carry the primary's invalid id.
    // After the cross-provider scrub it should be undefined / null (SDK default).
    expect(data.model, "model should not carry primary's gemini-3-flash id").not.toBe("gemini-3-flash");
  });
});
